<?php

namespace AppBundle\Repository;

/**
 * blog_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blog_userRepository extends \Doctrine\ORM\EntityRepository
{
}
