<?php

namespace AppBundle\Repository;

/**
 * blog_postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blog_postRepository extends \Doctrine\ORM\EntityRepository
{
}
