<?php

namespace AppBundle\Repository;

/**
 * blog_tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blog_tagRepository extends \Doctrine\ORM\EntityRepository
{
}
