<?php

namespace AppBundle\Repository;

/**
 * blog_post_to_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blog_post_to_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
